# Generated by Django 2.2.1 on 2019-05-16 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=20)),
                ('grupos', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_txt', models.CharField(max_length=400)),
                ('metodo', models.CharField(max_length=200)),
                ('imagen', models.CharField(blank='true', default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=1)),
                ('alias', models.CharField(default='', max_length=5)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaOriginal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=10)),
                ('res', models.CharField(max_length=10)),
                ('generate_method', models.CharField(max_length=100)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaAleatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250)),
                ('variable', models.CharField(max_length=10)),
                ('res', models.CharField(max_length=100)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Unidad'),
        ),
    ]
