# Generated by Django 2.1.7 on 2019-03-07 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_txt', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_txt', models.CharField(max_length=200)),
                ('pregunta_txt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Pregunta')),
            ],
        ),
    ]
