# Generated by Django 2.1.7 on 2019-03-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='pregunta_txt',
            new_name='pregunta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='created',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='res_txt',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='orden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='res',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
