# Generated by Django 2.1.7 on 2019-03-07 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20190307_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaOriginal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.IntegerField()),
                ('orden', models.IntegerField()),
                ('limite_inicial', models.IntegerField()),
                ('limite_final', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Respuesta',
            new_name='RespuestaAleatoria',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='materia',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='metodo',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestaoriginal',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Pregunta'),
        ),
    ]
