# Generated by Django 2.2.1 on 2019-06-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_respuestaoriginal_mostrar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=250)),
                ('orden', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Pregunta')),
            ],
        ),
    ]
