# Generated by Django 2.1.7 on 2019-03-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20190307_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaoriginal',
            name='variable',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
