# Generated by Django 2.1.7 on 2019-03-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20190307_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaaleatoria',
            name='marca',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
