# Generated by Django 2.1.7 on 2019-03-16 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_respuestaaleatoria_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='unidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
