# Generated by Django 2.1.7 on 2019-03-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_pregunta_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='unidad',
            field=models.CharField(max_length=1),
        ),
    ]
