# Generated by Django 2.1.7 on 2019-03-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20190316_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='unidad',
        ),
    ]
