# Generated by Django 2.1.7 on 2019-03-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_remove_pregunta_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='unidad',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
