# Generated by Django 2.1.7 on 2019-03-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_pregunta_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaoriginal',
            name='limite_final',
        ),
        migrations.RemoveField(
            model_name='respuestaoriginal',
            name='limite_inicial',
        ),
        migrations.AddField(
            model_name='respuestaaleatoria',
            name='generate_method',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuestaaleatoria',
            name='res',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='respuestaoriginal',
            name='res',
            field=models.CharField(max_length=10),
        ),
    ]
