# Generated by Django 2.1.7 on 2019-03-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20190329_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaaleatoria',
            name='generate_method',
        ),
        migrations.AddField(
            model_name='respuestaoriginal',
            name='generate_method',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
